package com.simac.simacordre.enums;

public enum TypeDocumentPieceJointeEnum {
    FACTURE,RECU,BON_COMMANDE,CONTRAT,NOTE_SERVICE,LETTRE_OFFICIELLE,DEMANDE_ADMINISTRATIVE,RAPPORT,FORMULAIRE,JUSTIFICATIF,AUTRE
}